coffeeshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('login/', views.LoginView, name='login'),
    path('register/', views.RegisterView, name='register')
]

core/models.py
from django.db import models
from datetime import date, datetime
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
from django.utils import timezone

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length = 20, blank = False)
    price = models.IntegerField(blank = False)
    date_enrolled = models.DateField(default = timezone.now)
    available = models.BooleanField(default = True)
    orders_count = models.IntegerField(default = 0, editable = False)

    categories = [
        ('drink', 'Drink'),
        ('snack', 'Snack'),
        ('dessert', 'Dessert'),
        ('NA', 'NA')
    ]
    category = models.CharField(max_length = 20, choices = categories)

    def get_upload_path(instance, filename):
        return '{0}/{1}'.format(instance, filename)
    image = models.ImageField(upload_to = get_upload_path)

    def __str__(self):
        return self.title
    

class Order(models.Model):
    customer = models.ForeignKey('Customer', on_delete = models.CASCADE)
    date_issued = models.DateTimeField(default = datetime.now, blank = False)
    fullfilled = models.BooleanField(default = False)

    def __str__(self):
        return self.id 
    

class OrderItem(models.Model):
    '''NOTE:
    this model creates an intermediary table between an order and products. connecting orders and products directly will
    oblige creating more product objects for each order object, we use order items to separate orders and products
    '''
    
    item = models.ForeignKey('Item', on_delete = models.RESTRICT, blank = False)
    order = models.ForeignKey('Order', on_delete = models.RESTRICT, blank = False)
    quantity = models.IntegerField(default = 1, blank = False)

    def __str__(self):
        return self.id
    

class Payment(models.Model):
    order = models.OneToOneField('Order', on_delete = models.CASCADE, editable = False)
    customer = models.CharField(max_length = 20, editable = False)
    net = models.IntegerField(editable = False) 
    discount = models.IntegerField(default = 0, blank = True)

    #overriding the save() method
    def save(self, *args, **kwargs):
        #define customer name
        self.customer = self.order.customer.name
        #define net price
        self.net = sum([orderitem.item.price for i, orderitem in self.order.orderitem_set.all()])

        super().save(*args, **kwargs)

    def __str__(self):
        return "payment for order {}".format(self.order.id)
    

class Reservation(models.Model):
    customer = models.ForeignKey('Customer', on_delete = models.CASCADE, blank = True)
    date_issued = models.DateTimeField(blank = False)
    QR = models.ImageField(upload_to= 'QRs/%Y/%m/%d')    
    count = [
        ('1',1),
        ('2',2),
        ('3',3),
        ('4',4)
    ]
    people_count = models.IntegerField('persons', default = 1, choices = count)

    def __str__(self):
        return self.id
    

class Customer(models.Model):
    account = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    phone = models.IntegerField(blank = False, null = False)
    points = models.IntegerField(default = 0, editable = False)
    profits = models.IntegerField(default = 0, editable = False)

    def __str__(self):
        return str(self.account)

core/views.py
from .models import Customer
from .helper.functions import check_password
from .helper.Exceptions import *
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db.utils import IntegrityError, DataError
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
def IndexView(request):
    return render(request, 'core/index.html')

def LoginView(request):
    '''the code that runs when requesting the login page'''

    if request.method == 'POST':
        '''check and authenticate credentials'''
        
        # fetch client input from http request 
        try:
            username = request.POST['uname']
            password = request.POST['pswd']
            if username == '' or password == '': raise KeyError
        except KeyError:
            return render(request, 'core/login.html', {'error':MissingUnamePswd})
        #authenticate user:
        user = authenticate(username=username, password=password)
        if not user:
            return render(request, 'core/login.html',{'error':IncorrectUnamePswd})
        else:
            login(request, user)

        #redirect to index page
        return HttpResponseRedirect(reverse('core:index'))
    
    else: #request.method == 'GET':
        return render(request, 'core/login.html', {})

    
def RegisterView(request):
    '''the code that runs when requesting the register page'''

    if request.method == 'POST':
        # fetch client input from http request 
        try:
            username = request.POST['uname']
            password = request.POST['pswd']
            email = request.POST['email']
            phone = request.POST['phone']
            if username == '' or password == '' or email == '' or phone is None: raise KeyError
        except KeyError:
            return render(request, 'core/register.html', {'error':MissingCredentials})

        # check password rules
        error = check_password(password)
        if error:
            return render(request, 'core/register.html', {'error':error})
        
        # create user and assign to customer group
        User = get_user_model()
        customer_group = Group.objects.get(name='customer')
        try:
            user = User.objects.create_user(username = username, password = password, email = email)
            user.groups.add(customer_group)
            user.save()
        except (IntegrityError, DataError ) as e:
            return render(request, 'core/login.html', {'error':e})
        
        # create customer entry and link to user
        customer = Customer.objects.create(account = user, phone = phone)
        customer.save()
        #attach user to request, and redirect to index page
        login(request, user)
        return HttpResponseRedirect(reverse('core:index'))
    
    else: #request.method == 'GET':
        return render(request, 'core/register.html', {})

        



        
        
        






            
            
        

        
        

        

        
        

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="../../static/core/index.css" rel="stylesheet"/>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>

<body>
    <!-- NAVBAR -->

    <!-- BODY CONTENT -->

    <!-- FOOTER -->
</body>

core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Index</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="../../static/core/index.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- BANNERS -->
    <div class="container-fluid text-center">
      <div class="row g-0 banner">
        <div class="col-md-6 order-md-first">
          <img class="img-fluid" id="banner_img_1" src="../../static/core/1.jpg"/>
        </div>
        <div class="col-md-6 order-md-last" id="banner_text_1">
          <span>Indulge in the finest of coffee in the world that is roasted with expertise and care</span>
          <button><span>Order Now</span></button>
        </div>
      </div>
      <div class="row g-0 banner">
        <div class="col-md-6 order-md-first" id="IMG3">
          <img class="img-fluid" id="banner_img_3" src="../../static/core/3.jpg"/>
        </div>
        <div class="col-md-6 order-md-last" id="banner_text_3">
          <span>Our coffee is sourced from sustainable farms that care for the farmers and the environment</span>
          <button><span>Discover Our Coffee Sources</span></button>
        </div>
      </div>
      <div class = "row g-0 banner">
        <div class="col-md-6 order-md-last">
          <img class="img-fluid" id="banner_img_2" src="../../static/core/2.jpg"/>
        </div>
        <div class="col-md-6 order-md-first" id="banner_text_2">
          <span>Our methods consider roasting as an art that should be respected and cared for</span>
          <button><span>Buy Coffee Beans</span></button>
        </div>
      </div>
    </div>
  </body>

</html>

core/templates/core/login.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <style>
    .form{
      display: block;
      margin-left:auto;
      margin-right:auto;
      width:15%;
    }
    .field{
      margin-bottom: 30px;
    }
  </style>

  <body class="form">
    <p>Welcome :)</p>
    <p>Please login</p>
    <form method = 'post' action="{% url 'core:login'%}">
      {% csrf_token %}
      <div class="field">
        <label for="uname">Username: </label> <br>
        <input type='text' id="uname" name="uname">
      </div>
      <div class="field">
        <label for="password">Password: </label> <br>
        <input type="password" id="password" name="pswd">
      </div>
      {% if error %} <p><strong>{{error}}</strong></p> {% endif %}<br>
      <a href="{% url 'core:register' %}"> New customer?</a> <br><br>
      <input type="submit" value="Submit">
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/register.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <style>
    .form{
      display: block;
      margin-left:auto;
      margin-right:auto;
      width:15%;
    }
    .field{
      margin-bottom: 30px;
    }
    input{
      width : 250px;
    }
  </style>

  <body class="form">
    <p>Welcome :)</p>
    
    <form method="post" action="{% url 'core:register' %}">
        {% csrf_token %}
        <p>Please let us know more about you</p><br>
        <div class="field">
            <label for="phone">Phone:</label><br>
            <input type=" tel" id="phone" name="phone">
        </div>
        <div class="field">
            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email">
        </div>
        <p>Please provide your credentials</p><br>
        <div class="field">
            <label for="username">Username:</label><br>
            <input type="text" id="username" name="uname">
        </div>
        <div class="field">
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="pswd">
        </div>
        {% if error %}<p><strong>{{ error }}</strong></p>{% endif %}
        <br>
        <a href="{% url 'core:login' %}">Already a customer?</a><br><br>
        <input type="submit">
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>